name: flutter_video_app
description: Part of webview_camera_maps_playback_flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluro: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  video_player: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/